language: cpp
sudo: required
dist: xenial
before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
install:
    - sudo apt-get install -y cmake build-essential curl libgoogle-glog-dev libjansson-dev libjsoncpp-dev libcurl4-gnutls-dev libgflags-dev openssl libssl-dev libboost1.55-all-dev
    - sudo ln -sf /usr/include/jsoncpp/json /usr/include/json

    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-5 gcc-5; fi
    - if [ "$CXX" == "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.7; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
script: cmake . && make
compiler:
    - gcc
