language: cpp
sudo: required
dist: xenial
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake build-essential curl libgoogle-glog-dev libjansson-dev libjsoncpp-dev libcurl4-gnutls-dev libgflags-dev openssl libssl-dev
  - sudo ln -sf /usr/include/jsoncpp/json /usr/include/json
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
script: cmake . && make
compiler:
    - gcc